[build]
  command = "git clone https://github.com/flutter/flutter.git -b stable --depth 1 $HOME/flutter && export PATH=$PATH:$HOME/flutter/bin && echo \"$FIREBASE_OPTIONS_DART\" | base64 --decode > lib/firebase_options.dart && flutter pub get && flutter build web --release --dart-define=ENVIRONMENT=production"
  publish = "build/web"

[build.environment]
  NODE_VERSION = "18"