import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';

ThemeData darkMode = ThemeData(
  useMaterial3: true,
  colorScheme: const ColorScheme.dark(
    primary: Color(0xFF8BC48A),
    onPrimary: Color(0xFF003909),
    primaryContainer: Color(0xFF1B5120),
    onPrimaryContainer: Color(0xFFA7F3A6),
    secondary: Color(0xFFA3B8A1),
    onSecondary: Color(0xFF1B2E1B),
    secondaryContainer: Color(0xFF1E3121),
    onSecondaryContainer: Color(0xFFBFD4BD),
    surface: Color(0xFF0F120F),
    onSurface: Color(0xFFE1E3E0),
    surfaceContainerLowest: Color(0xFF090C09),
    surfaceContainerLow: Color(0xFF171A17),
    surfaceContainer: Color(0xFF1B1F1B),
    surfaceContainerHigh: Color(0xFF252925),
    surfaceContainerHighest: Color(0xFF303430),
    onSurfaceVariant: Color(0xFFBDC9BB),
    outline: Color(0xFF87938A),
    outlineVariant: Color(0xFF3A4A3A),
    error: Color(0xFFFFB4AB),
    onError: Color(0xFF690005),
    inverseSurface: Color(0xFFE1E3E0),
    onInverseSurface: Color(0xFF2E312E),
    inversePrimary: Color(0xFF38563B),
    surfaceTint: Color(0xFF8BC48A),
  ),
  scaffoldBackgroundColor: const Color(0xFF0F120F),
  textTheme: GoogleFonts.plusJakartaSansTextTheme(ThemeData.dark().textTheme).copyWith(
    displayLarge: GoogleFonts.bebasNeue(fontSize: 48, letterSpacing: 1, color: const Color(0xFFE1E3E0)),
    displayMedium: GoogleFonts.bebasNeue(fontSize: 40, letterSpacing: 0.8, color: const Color(0xFFE1E3E0)),
    displaySmall: GoogleFonts.bebasNeue(fontSize: 32, letterSpacing: 0.6, color: const Color(0xFFE1E3E0)),
  ),
  cardTheme: CardThemeData(
    color: const Color(0xFF1B1F1B),
    elevation: 0,
    margin: EdgeInsets.zero,
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.circular(16),
      side: const BorderSide(color: Color(0xFF3A4A3A), width: 0.5),
    ),
  ),
  elevatedButtonTheme: ElevatedButtonThemeData(
    style: ElevatedButton.styleFrom(
      backgroundColor: const Color(0xFF1B5120),
      foregroundColor: const Color(0xFFA7F3A6),
      shape: const StadiumBorder(),
      padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 24),
      elevation: 0,
      textStyle: GoogleFonts.plusJakartaSans(fontSize: 15, fontWeight: FontWeight.w700),
    ),
  ),
  outlinedButtonTheme: OutlinedButtonThemeData(
    style: OutlinedButton.styleFrom(
      foregroundColor: const Color(0xFF8BC48A),
      side: const BorderSide(color: Color(0xFF3A4A3A)),
      shape: const StadiumBorder(),
      padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 24),
      textStyle: GoogleFonts.plusJakartaSans(fontSize: 15, fontWeight: FontWeight.w600),
    ),
  ),
  inputDecorationTheme: InputDecorationTheme(
    filled: true,
    fillColor: const Color(0xFF171A17),
    border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: Color(0xFF3A4A3A))),
    enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: Color(0xFF3A4A3A))),
    focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: Color(0xFF8BC48A), width: 2)),
    errorBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: Color(0xFFFFB4AB))),
    labelStyle: const TextStyle(fontSize: 12, fontWeight: FontWeight.w700, color: Color(0xFFBDC9BB)),
    hintStyle: const TextStyle(color: Color(0xFF87938A)),
    contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
  ),
  bottomNavigationBarTheme: const BottomNavigationBarThemeData(
    backgroundColor: Color(0xFF1B1F1B),
    selectedItemColor: Color(0xFF8BC48A),
    unselectedItemColor: Color(0xFF87938A),
    selectedLabelStyle: TextStyle(fontWeight: FontWeight.w600, fontSize: 11),
    unselectedLabelStyle: TextStyle(fontWeight: FontWeight.w400, fontSize: 11),
    elevation: 0,
    type: BottomNavigationBarType.fixed,
  ),
  appBarTheme: const AppBarTheme(
    backgroundColor: Color(0xFF0F120F),
    elevation: 0,
    scrolledUnderElevation: 0,
    iconTheme: IconThemeData(color: Color(0xFFE1E3E0)),
    centerTitle: false,
    systemOverlayStyle: SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.light,
      statusBarBrightness: Brightness.dark,
    ),
  ),
  dividerTheme: const DividerThemeData(color: Color(0xFF3A4A3A), thickness: 0.5, space: 0),
  chipTheme: ChipThemeData(
    backgroundColor: const Color(0xFF1B1F1B),
    selectedColor: const Color(0xFF1E3121),
    side: BorderSide.none,
    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
  ),
  tabBarTheme: const TabBarThemeData(
    labelColor: Color(0xFFE1E3E0),
    unselectedLabelColor: Color(0xFF87938A),
    indicatorSize: TabBarIndicatorSize.tab,
    dividerColor: Colors.transparent,
  ),
);
